// <auto-generated />
using System;
using Desafio3_DES.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio3_DES.Migrations
{
    [DbContext(typeof(RecetasDBContext))]
    [Migration("20261008033755_Identity_y_CorreccionSeeds")]
    partial class Identity_y_CorreccionSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio3_DES.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngrediente"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIngrediente");

                    b.HasIndex("RecetaId");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            IdIngrediente = -1,
                            Cantidad = 1,
                            NombreIngrediente = "Lechuga romana",
                            RecetaId = -1,
                            UnidadMedida = "Unidad"
                        },
                        new
                        {
                            IdIngrediente = -2,
                            Cantidad = 200,
                            NombreIngrediente = "Pollo a la parrilla",
                            RecetaId = -1,
                            UnidadMedida = "Gramos"
                        },
                        new
                        {
                            IdIngrediente = -3,
                            Cantidad = 50,
                            NombreIngrediente = "Aderezo César",
                            RecetaId = -1,
                            UnidadMedida = "Mililitros"
                        },
                        new
                        {
                            IdIngrediente = -4,
                            Cantidad = 250,
                            NombreIngrediente = "Pasta espagueti",
                            RecetaId = -2,
                            UnidadMedida = "Gramos"
                        },
                        new
                        {
                            IdIngrediente = -5,
                            Cantidad = 100,
                            NombreIngrediente = "Crema de leche",
                            RecetaId = -2,
                            UnidadMedida = "Mililitros"
                        },
                        new
                        {
                            IdIngrediente = -6,
                            Cantidad = 1,
                            NombreIngrediente = "Huevo",
                            RecetaId = -2,
                            UnidadMedida = "Unidad"
                        },
                        new
                        {
                            IdIngrediente = -7,
                            Cantidad = 50,
                            NombreIngrediente = "Queso parmesano",
                            RecetaId = -2,
                            UnidadMedida = "Gramos"
                        },
                        new
                        {
                            IdIngrediente = -8,
                            Cantidad = 500,
                            NombreIngrediente = "Tomates frescos",
                            RecetaId = -3,
                            UnidadMedida = "Gramos"
                        },
                        new
                        {
                            IdIngrediente = -9,
                            Cantidad = 5,
                            NombreIngrediente = "Albahaca",
                            RecetaId = -3,
                            UnidadMedida = "Hojas"
                        });
                });

            modelBuilder.Entity("Desafio3_DES.Models.PasosPreparacion", b =>
                {
                    b.Property<int>("IdPaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaso"));

                    b.Property<string>("DescripcionPaso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenPaso")
                        .HasColumnType("int");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.HasKey("IdPaso");

                    b.HasIndex("RecetaId");

                    b.ToTable("PasosPreparacion");

                    b.HasData(
                        new
                        {
                            IdPaso = -1,
                            DescripcionPaso = "Lavar la lechuga romana y cortarla en trozos.",
                            OrdenPaso = 1,
                            RecetaId = -1
                        },
                        new
                        {
                            IdPaso = -2,
                            DescripcionPaso = "Asar el pollo a la parrilla y cortarlo en tiras.",
                            OrdenPaso = 2,
                            RecetaId = -1
                        },
                        new
                        {
                            IdPaso = -3,
                            DescripcionPaso = "Mezclar la lechuga, el pollo y el aderezo César.",
                            OrdenPaso = 3,
                            RecetaId = -1
                        },
                        new
                        {
                            IdPaso = -4,
                            DescripcionPaso = "Cocinar la pasta en agua hirviendo con sal.",
                            OrdenPaso = 1,
                            RecetaId = -2
                        },
                        new
                        {
                            IdPaso = -5,
                            DescripcionPaso = "Mezclar el huevo, la crema y el queso parmesano.",
                            OrdenPaso = 2,
                            RecetaId = -2
                        },
                        new
                        {
                            IdPaso = -6,
                            DescripcionPaso = "Añadir la mezcla a la pasta caliente.",
                            OrdenPaso = 3,
                            RecetaId = -2
                        },
                        new
                        {
                            IdPaso = -7,
                            DescripcionPaso = "Cortal los tomates y hervirlos hasta que se ablanden.",
                            OrdenPaso = 1,
                            RecetaId = -3
                        },
                        new
                        {
                            IdPaso = -8,
                            DescripcionPaso = "Licuar los tomates y agregar la albahaca.",
                            OrdenPaso = 2,
                            RecetaId = -3
                        },
                        new
                        {
                            IdPaso = -9,
                            DescripcionPaso = "Cocinar por 10 miutos y servir caliente.",
                            OrdenPaso = 3,
                            RecetaId = -3
                        });
                });

            modelBuilder.Entity("Desafio3_DES.Models.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreReceta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("TiempoPreparacion")
                        .HasColumnType("time");

                    b.HasKey("IdReceta");

                    b.ToTable("Recetas");

                    b.HasData(
                        new
                        {
                            IdReceta = -1,
                            Descripcion = "Ensalada clásica con pollo, lechuga y aderezo César.",
                            NombreReceta = "Ensalada César",
                            TiempoPreparacion = new TimeOnly(0, 20, 0)
                        },
                        new
                        {
                            IdReceta = -2,
                            Descripcion = "Pasta con salsa de crema, huevo y queso parmesano.",
                            NombreReceta = "Pasta Carbonara",
                            TiempoPreparacion = new TimeOnly(0, 30, 0)
                        },
                        new
                        {
                            IdReceta = -3,
                            Descripcion = "Sopa ligera de tomate con albahaca.",
                            NombreReceta = "Sopa de Tomate",
                            TiempoPreparacion = new TimeOnly(0, 40, 0)
                        });
                });

            modelBuilder.Entity("Desafio3_DES.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Desafio3_DES.Models.Ingrediente", b =>
                {
                    b.HasOne("Desafio3_DES.Models.Receta", "Receta")
                        .WithMany("Ingredientes")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Desafio3_DES.Models.PasosPreparacion", b =>
                {
                    b.HasOne("Desafio3_DES.Models.Receta", "Receta")
                        .WithMany("PasosPreparacion")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Desafio3_DES.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Desafio3_DES.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Desafio3_DES.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Desafio3_DES.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desafio3_DES.Models.Receta", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("PasosPreparacion");
                });
#pragma warning restore 612, 618
        }
    }
}
